copy abstract_factory\*.* . /y
copy adapter\*.* . /y
copy bridge\*.* . /y
copy builder\*.* . /y
copy chain_of_responsibility\*.* . /y
copy command\*.* . /y
copy composite\*.* . /y
copy decorator\*.* . /y
copy facade\*.* . /y
copy factory\*.* . /y
copy flyweight\*.* . /y
copy interpreter\*.* . /y
copy iterator\*.* . /y
copy mediator\*.* . /y
copy memento\*.* . /y
copy observer\*.* . /y
copy prototype\*.* . /y
copy proxy\*.* . /y
copy singleton\*.* . /y
copy state\*.* . /y
copy strategy\*.* . /y
copy template\*.* . /y
copy visitor\*.* . /y